# Generated by Django 4.1.7 on 2023-06-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_technology_id_alter_usernet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='technology',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
