# Generated by Django 4.1.7 on 2023-06-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_usernet_technology_delete_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='avatar',
        ),
    ]
